import Link from 'next/link';

const features = [
  {
    title: 'Live transcription',
    description:
      'Record a lecture in the browser and watch the transcript appear in real time, powered by Google Cloud Speech-to-Text.',
  },
  {
    title: 'Plain-language explanations',
    description:
      'Stuck on a term? Ask for a short, student-friendly explanation generated by an AI model.',
  },
  {
    title: 'Translation',
    description:
      'Translate transcripts into ten languages so lectures are easier to follow in the language you think in.',
  },
];

export default function Home() {
  return (
    <div className="mx-auto max-w-5xl px-4 py-16">
      <section className="text-center">
        <p className="mb-3 text-sm font-semibold uppercase tracking-wide text-blue-600">
          AI lecture assistant · MVP
        </p>
        <h1 className="!mt-0 text-4xl font-extrabold tracking-tight sm:text-5xl">
          Follow every lecture, in any language
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-600 dark:text-gray-300">
          PolyGO transcribes lectures, explains hard terms in plain language and translates them, so
          you spend less time catching up and more time understanding.
        </p>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
          <Link
            href="/auth/signup"
            className="rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white shadow-sm transition hover:bg-blue-700"
          >
            Get started
          </Link>
          <Link
            href="/auth/signin"
            className="rounded-lg border border-gray-300 px-6 py-3 font-semibold text-gray-800 transition hover:bg-white dark:border-gray-600 dark:text-gray-100 dark:hover:bg-gray-800"
          >
            Sign in
          </Link>
          <Link
            href="/lectures"
            className="px-2 py-3 font-semibold text-blue-600 hover:underline"
          >
            My lectures →
          </Link>
        </div>
      </section>

      <section className="mt-20 grid gap-6 sm:grid-cols-3">
        {features.map((feature) => (
          <div key={feature.title} className="card">
            <h3 className="!mb-2 !text-xl">{feature.title}</h3>
            <p className="text-gray-600 dark:text-gray-300">{feature.description}</p>
          </div>
        ))}
      </section>

      <p className="mt-16 text-center text-sm text-gray-500">
        PolyGO is an early prototype built as a university project. Development is currently paused.
      </p>
    </div>
  );
}
